apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-argocd
  template:
    metadata:
      labels:
        app: flask-argocd
    spec:
      containers:
      - name: flask-argocd
        image: ghcr.io/emiakia/flask-argocd:v01
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ghcr-secret
